### ISSUE TITLE
RegisteredAlbumのファイルのうち、1件目のファイルしか取得できない

### ISSUE THREAD

**Issue by xm-i** [southernwind/MediaBox#5]
おそらくこの問題
https://github.com/mbdavid/LiteDB/issues/1358
 Closedだけど、v5-beta時点では当該コミットが反映されていない
次回アップデートでたぶんなおる。

**Comment by southernwind** [comment]
最新バージョンをコンパイルして置き換えて試して修正されていることを確認
待ち

**Comment by xm-i** [comment]
最新のソースのものをコンパイルして置き換えると問題が解決されることを確認
次回アップデート適用後Closeする。
